name: "Multi event pipeline/workflow"


on:
  push: # Event :Whenever a push is made to the repository on the master branch
      branch:
         - master
         - test
         

jobs:
  "event pipeline":
   runs-on:  ubuntu-latest
   steps: # steps to be executed in the job
     name: "Running on master Push" #step 1
     run : echo "Running on master push"
    
 