name: "Multi event pipeline/workflow"


on:
  push: # Event :Whenever a push is made to the repository on the master branch
      branches:
         - master
         - test

  schedule: 
    -  cron: "0 10 * * 2,4"

  pull_request:  # Event :Whenever a pull is made to the repository on the master branch
      branches:
        - master
        - test
  
         

jobs:
  on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: 
           - name: "Running on master Push" 
             run : echo "Running on master/test push"
    
  on-pull:
        if: github.event_name == 'pull'
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on master Push"
              run  :  echo "Running on master/test pull"

  on-sechudle: 
         if: github.event_name == 'schedule'
         runs-on: ubuntu-latest
         steps:
           - name: "Running on sechudle time"
             run: echo " Running At 10:00 on Tuesday and Thursday."
