name: "deveops-paractice"

on:
  push:
    branches:
     - master

jobs:
  "hello-world":
   runs-on: ubuntu-latest
   steps:
    - name: "Print hello world"
      run:echo "Hello world"

     
